# Generated by Django 6.1.1 on 2026-10-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='about',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
