# Generated by Django 6.1.1 on 2026-10-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
